//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JavascriptLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apply_Sub_CashChange
    {
        public int ID { get; set; }
        public int Apply_Sub_ID { get; set; }
        public Nullable<int> InUserBankID { get; set; }
        public Nullable<int> OutUserBankID { get; set; }
        public decimal iMoney { get; set; }
        public string CType { get; set; }
    }
}
