//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JavascriptLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apply_Sub_JieKuan
    {
        public int ID { get; set; }
        public int Apply_Sub_ID { get; set; }
        public string JiechuUserName { get; set; }
        public System.DateTime JiechuDate { get; set; }
        public string HuanKuanUserName { get; set; }
        public Nullable<System.DateTime> HuanKuanAboutDate { get; set; }
        public string HuanKuanDate { get; set; }
        public string CAdd { get; set; }
    
        public virtual Apply_Sub Apply_Sub { get; set; }
    }
}
