//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JavascriptLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apply_Main
    {
        public Apply_Main()
        {
            this.Apply_Sub = new HashSet<Apply_Sub>();
        }
    
        public int ID { get; set; }
        public int ApplyUserID { get; set; }
        public System.DateTime ApplyDate { get; set; }
        public decimal ApplyInMoney { get; set; }
        public decimal ApplyOutMoney { get; set; }
        public int iyear { get; set; }
        public int imonth { get; set; }
        public int iday { get; set; }
        public Nullable<decimal> iNowCashMoney { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Apply_Sub> Apply_Sub { get; set; }
    }
}
