//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JavascriptLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysModel
    {
        public SysModel()
        {
            this.UserModelPowers = new HashSet<UserModelPower>();
        }
    
        public int ID { get; set; }
        public string SysModelName { get; set; }
        public string SysModelPhyURL { get; set; }
        public string SysModelRouteName { get; set; }
        public string SysModelController { get; set; }
        public string SysModelAction { get; set; }
        public string SysModelRel { get; set; }
        public string SysModelTarget { get; set; }
        public string SysModelUrlPram { get; set; }
        public int SysModelClassID { get; set; }
        public int SysModelLevel { get; set; }
        public bool IsLast { get; set; }
        public bool IsHaveAction { get; set; }
        public bool IsFlag { get; set; }
    
        public virtual ICollection<UserModelPower> UserModelPowers { get; set; }
    }
}
