//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JavascriptLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Apply_Main = new HashSet<Apply_Main>();
            this.UserModelPowers = new HashSet<UserModelPower>();
        }
    
        public int ID { get; set; }
        public int cUserCode { get; set; }
        public string cUserName { get; set; }
        public string cUserSex { get; set; }
        public int cUserRole { get; set; }
        public string cUserPwd { get; set; }
        public Nullable<System.DateTime> cUserBirthday { get; set; }
        public string cUserSayword { get; set; }
        public bool cUserFlag { get; set; }
        public System.DateTime dCreateDate { get; set; }
    
        public virtual ICollection<Apply_Main> Apply_Main { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<UserModelPower> UserModelPowers { get; set; }
    }
}
