//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JavascriptLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserModelPower
    {
        public int ID { get; set; }
        public int modelID { get; set; }
        public int userID { get; set; }
        public int modelButtonID { get; set; }
    
        public virtual SysModel SysModel { get; set; }
        public virtual User User { get; set; }
    }
}
